### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by bamtan** [petercunha/tts#11]
Is it being rate-limited now? Or has something changed in the backend?

**Comment by mr555ru** [comment]
Confirm, returns 429: Streamlabs API error. [https://imgur.com/Y6Me43s](https://imgur.com/Y6Me43s)

EDIT: It works sometimes though. Could it be someone overloading the service?

**Comment by bamtan** [comment]
I think it may be rate-limited. Closing this issue!

**Comment by petercunha** [comment]
Looking into this. Thanks for the heads up.

**Comment by petercunha** [comment]
Yes, looks like rate limiting on the streamlabs API. Not sure if there's anything I can do to fix that :-/

**Comment by petercunha** [comment]
Thanks again for reporting this. 

I added some client side rate limiting and captcha for suspicious browsers, hopefully this will help.
